/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { ModelProps } from "./model"

type GLTFResult = GLTF & {
  nodes: {
    Plane012_1: THREE.Mesh
    Plane012_2: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube008_1: THREE.Mesh
    Cube008_2: THREE.Mesh
    Plane044_1: THREE.Mesh
    Plane044_2: THREE.Mesh
    Plane047_1: THREE.Mesh
    Plane047_2: THREE.Mesh
    Cube011_1: THREE.Mesh
    Cube011_2: THREE.Mesh
    Cube022_1: THREE.Mesh
    Cube022_2: THREE.Mesh
    Cube034: THREE.Mesh
    Cube034_1: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube024_2: THREE.Mesh
    Cube024_3: THREE.Mesh
    Plane040_1: THREE.Mesh
    Plane040_2: THREE.Mesh
    Plane038: THREE.Mesh
    Cylinder032: THREE.Mesh
    Cylinder032_1: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane014_2: THREE.Mesh
    Plane014_1: THREE.Mesh
    Cylinder038: THREE.Mesh
    Cylinder038_1: THREE.Mesh
    Cube030_1: THREE.Mesh
    Cube030_2: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube007_2: THREE.Mesh
    Cylinder030: THREE.Mesh
    Cylinder030_1: THREE.Mesh
    Cylinder031: THREE.Mesh
    Cylinder031_1: THREE.Mesh
    Cylinder037_1: THREE.Mesh
    Cylinder037: THREE.Mesh
    Cylinder036: THREE.Mesh
    Cylinder036_1: THREE.Mesh
    Plane029_1: THREE.Mesh
    Plane029_2: THREE.Mesh
    Plane030_1: THREE.Mesh
    Plane030_2: THREE.Mesh
    Plane031_1: THREE.Mesh
    Plane031_2: THREE.Mesh
    Plane032_1: THREE.Mesh
    Plane032_2: THREE.Mesh
    Plane033_1: THREE.Mesh
    Plane033_2: THREE.Mesh
    Plane025_1: THREE.Mesh
    Plane025_2: THREE.Mesh
    Plane025_3: THREE.Mesh
    Cylinder021: THREE.Mesh
    Cylinder021_1: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder016_2: THREE.Mesh
    Cylinder016_1_1: THREE.Mesh
    Cylinder016_2_1: THREE.Mesh
    Cylinder016_1_2: THREE.Mesh
    Cylinder016_2_2: THREE.Mesh
    Cylinder016_1_3: THREE.Mesh
    Cylinder016_2_3: THREE.Mesh
    Plane013: THREE.Mesh
    Plane010: THREE.Mesh
    Plane009: THREE.Mesh
    Plane007: THREE.Mesh
    Plane006: THREE.Mesh
    Plane005: THREE.Mesh
    Plane004: THREE.Mesh
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Cube001: THREE.Mesh
    Sphere002: THREE.Mesh
    Plane022: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Plane039: THREE.Mesh
    Plane040: THREE.Mesh
    Cube018: THREE.Mesh
    Plane042: THREE.Mesh
    Plane043: THREE.Mesh
    Plane046: THREE.Mesh
    Cube021: THREE.Mesh
    Plane048: THREE.Mesh
    Plane049: THREE.Mesh
    Cube029: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Sphere: THREE.Mesh
    Plane052: THREE.Mesh
    Plane011: THREE.Mesh
    Plane047: THREE.Mesh
    Plane017: THREE.Mesh
    Plane021: THREE.Mesh
    Cylinder014: THREE.Mesh
    Cube024: THREE.Mesh
    Cube023: THREE.Mesh
    Cube027: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Plane026: THREE.Mesh
    Plane015: THREE.Mesh
    Cylinder: THREE.Mesh
    Bolt: THREE.Mesh
    Bolt001: THREE.Mesh
    Bolt002: THREE.Mesh
    Plane019: THREE.Mesh
    Plane020: THREE.Mesh
    Plane035: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Plane018: THREE.Mesh
    Torus: THREE.Mesh
    Plane045: THREE.Mesh
    Plane008: THREE.Mesh
    Cube008: THREE.Mesh
    Cube005: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube010: THREE.Mesh
    Cylinder010: THREE.Mesh
    Plane002: THREE.Mesh
    Plane027: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Plane024: THREE.Mesh
    Cube020: THREE.Mesh
    Cube014: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Plane025: THREE.Mesh
    Plane029: THREE.Mesh
    Plane034: THREE.Mesh
    Plane037: THREE.Mesh
    Cube035: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder019: THREE.Mesh
  }
  materials: {
    Rubber: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
    ['Chrome.003']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Rubber.001']: THREE.MeshStandardMaterial
    ['matte-black']: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    tire_tread: THREE.MeshStandardMaterial
    tire_side: THREE.MeshStandardMaterial
    Cluster: THREE.MeshStandardMaterial
    ['Cristal.001']: THREE.MeshStandardMaterial
    paint: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Chrome.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    lightbulb: THREE.MeshStandardMaterial
    ['Rubber.003']: THREE.MeshStandardMaterial
    ['metal.001']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    Cristal: THREE.MeshStandardMaterial
    Seats: THREE.MeshStandardMaterial
    ['Rubber.002']: THREE.MeshStandardMaterial
    ['metal.002']: THREE.MeshStandardMaterial
    ['Cristal.002']: THREE.MeshStandardMaterial
    Exhaust: THREE.MeshStandardMaterial
  }
}

export default function Car(props: ModelProps) {
  const { nodes, materials } = useGLTF('/scene.gltf') as unknown as  GLTFResult

  return (
    <group name="Scene" rotation={[0, 3.14, 0]} {...props} dispose={null} >
      <group position={[0, 0.71, 0]}>
        <group position={[0, 0.4, 0]} scale={[0.02, 0.02, 0.02]}>
          <group position={[0, -17.5222, 177.4529]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Plane012_1.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Plane012_2.geometry} material={materials.Chrome} />
          </group>
          <group position={[-34.2674, 22.2363, 81.8952]} rotation={[0.0069, 0.0012, 0.06]} scale={[1, 1, 1]}>
            <mesh geometry={nodes.Cube006_1.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Cube006_2.geometry} material={materials.Rubber} />
          </group>
          <group position={[0, 23.0602, 82.35]} rotation={[0.0186, 0, 0]}>
            <mesh geometry={nodes.Cube008_1.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Cube008_2.geometry} material={materials.Rubber} />
          </group>
          <group position={[0, -1.6132, -100.1712]}>
            <mesh geometry={nodes.Plane044_1.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Plane044_2.geometry} material={materials.Rubber} />
          </group>
          <group position={[-63.9331, 18.9587, -20.1118]} scale={[-0.0772, 0.0772, 0.0772]}>
            <mesh geometry={nodes.Plane047_1.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Plane047_2.geometry} material={materials.Rubber} />
          </group>
          <group position={[0.0111, 46.6859, -20.0682]} rotation={[0.2988, -0.2505, 0.0778]} scale={[1, 1, 1]}>
            <mesh geometry={nodes.Cube011_1.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Cube011_2.geometry} material={materials['Chrome.003']} />
          </group>
          <group position={[-4.0557, -0.4777, -49.6404]}>
            <mesh geometry={nodes.Cube022_1.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Cube022_2.geometry} material={materials['Material.008']} />
          </group>
          <group position={[1.1415, -19.0838, 3.8412]}>
            <mesh geometry={nodes.Cube034.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Cube034_1.geometry} material={materials.Rubber} />
          </group>
          <group position={[-60.1745, -5.065, -12.9324]} rotation={[0, 0, -Math.PI / 2]}>
            <group position={[3.0605, 0.4719, 9.1836]} rotation={[0, 0, Math.PI / 2]}>
              <mesh geometry={nodes.Cube024_1.geometry} material={materials['Rubber.001']} />
              <mesh geometry={nodes.Cube024_2.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Cube024_3.geometry} material={materials['matte-black']} />
            </group>
            <mesh geometry={nodes.Plane040_1.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Plane040_2.geometry} material={materials.Chrome} />
            <mesh
              geometry={nodes.Plane038.geometry}
              material={materials.metal}
              position={[1.9531, 0.8392, -12.7178]}
              rotation={[0, 0.0639, Math.PI / 2]}
              scale={[1.3418, 1.3418, 1.3418]}
            />
          </group>
          <group
            position={[-59.9455, -7.3788, -38.8037]}
            rotation={[2.7463, 0, -Math.PI / 2]}
            scale={[0.0218, 0.0218, 0.0218]}>
            <mesh geometry={nodes.Cylinder032.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Cylinder032_1.geometry} material={materials.Rubber} />
          </group>
          <group position={[0, -1.6132, -100.1712]}>
            <mesh geometry={nodes.Plane003.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-61.4683, -29.1479, -98.9785]}>
            <mesh geometry={nodes.Plane014_2.geometry} material={materials.tire_tread} />
            <mesh geometry={nodes.Plane014_1.geometry} material={materials.tire_side} />
          </group>
          <group position={[-22.276, 21.2993, 111.2451]} rotation={[0.0752, 0, 0]} scale={[0.8081, 0.8081, 0.8081]}>
            <mesh geometry={nodes.Cylinder038.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder038_1.geometry} material={materials.Rubber} />
          </group>
          <group position={[-10.1606, 53.9258, -18.2943]}>
            <mesh geometry={nodes.Cube030_1.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cube030_2.geometry} material={materials.Rubber} />
          </group>
          <group position={[0.0111, 51.8871, -20.9519]}>
            <mesh geometry={nodes.Cube007_1.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Cube007_2.geometry} material={materials.metal} />
          </group>
          <group position={[0, 7.2189, -40.9722]} rotation={[1.3146, 0, 0]}>
            <mesh geometry={nodes.Cylinder030.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder030_1.geometry} material={materials.Rubber} />
          </group>
          <group position={[-4.7332, 7.2612, -40.7867]} rotation={[1.3467, 0, 0]}>
            <mesh geometry={nodes.Cylinder031.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder031_1.geometry} material={materials.Rubber} />
          </group>
          <group
            position={[-0.7644, -12.1, -28.8051]}
            rotation={[-0.1664, -0.1598, 0.167]}
            scale={[0.0076, 0.0076, 0.0076]}>
            <group position={[-0.0001, 2121.5337, 0.0637]} scale={[131.1593, 131.1593, 131.1593]}>
              <mesh geometry={nodes.Cylinder037_1.geometry} material={materials.metal} />
              <mesh geometry={nodes.Cylinder037.geometry} material={materials['matte-black']} />
            </group>
            <mesh geometry={nodes.Cylinder036.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder036_1.geometry} material={materials.Rubber} />
          </group>
          <mesh geometry={nodes.Plane029_1.geometry} material={materials['matte-black']} />
          <mesh geometry={nodes.Plane029_2.geometry} material={materials.Cluster} />
          <group position={[-17.7719, -0.1327, 1.5559]}>
            <mesh geometry={nodes.Plane030_1.geometry} material={materials['matte-black']} />
            <mesh geometry={nodes.Plane030_2.geometry} material={materials.Cluster} />
          </group>
          <group position={[-24.4764, -0.4357, 2.168]}>
            <mesh geometry={nodes.Plane031_1.geometry} material={materials['matte-black']} />
            <mesh geometry={nodes.Plane031_2.geometry} material={materials.Cluster} />
          </group>
          <group position={[-18.65, 0.0822, 1.6076]}>
            <mesh geometry={nodes.Plane032_1.geometry} material={materials['matte-black']} />
            <mesh geometry={nodes.Plane032_2.geometry} material={materials.Cluster} />
          </group>
          <mesh geometry={nodes.Plane033_1.geometry} material={materials['matte-black']} />
          <mesh geometry={nodes.Plane033_2.geometry} material={materials.Cluster} />
          <group position={[-69.8005, 7.3927, 38.82]} scale={[1.2143, 1.2143, 1.2143]}>
            <mesh geometry={nodes.Plane025_1.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Plane025_2.geometry} material={materials.metal} />
            <mesh geometry={nodes.Plane025_3.geometry} material={materials['matte-black']} />
          </group>
          <group position={[-17.0118, 2.516, -40.245]} rotation={[1.0344, 0, 0]}>
            <mesh geometry={nodes.Cylinder021.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder021_1.geometry} material={materials['matte-black']} />
          </group>
          <group
            position={[-51.8777, 12.1563, -38.8043]}
            rotation={[1.5773, 0.0087, -0.0849]}
            scale={[0.0075, 0.0075, 0.0075]}>
            <mesh geometry={nodes.Cylinder016_1.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder016_2.geometry} material={materials['matte-black']} />
          </group>
          <group
            position={[-49.0353, 12.1563, -39.0472]}
            rotation={[1.5776, 0.0087, -0.0854]}
            scale={[0.0075, 0.0075, 0.0075]}>
            <mesh geometry={nodes.Cylinder016_1_1.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder016_2_1.geometry} material={materials['matte-black']} />
          </group>
          <group
            position={[-46.193, 12.1563, -39.2905]}
            rotation={[1.5776, 0.0087, -0.0854]}
            scale={[0.0075, 0.0075, 0.0075]}>
            <mesh geometry={nodes.Cylinder016_1_2.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder016_2_2.geometry} material={materials['matte-black']} />
          </group>
          <group
            position={[-43.3507, 12.1563, -39.5352]}
            rotation={[1.5774, 0.0087, -0.0865]}
            scale={[0.0075, 0.0075, 0.0075]}>
            <mesh geometry={nodes.Cylinder016_1_3.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder016_2_3.geometry} material={materials['matte-black']} />
          </group>
          <mesh geometry={nodes.Plane013.geometry} material={materials.Chrome} position={[0, -1.6132, -100.1712]} />
          <mesh material-color={props.interior} geometry={nodes.Plane010.geometry} material={materials.Rubber} position={[0, -1.6132, -100.1712]} />
          <mesh
            geometry={nodes.Plane009.geometry}
            material={materials['Cristal.001']}
            position={[0, -1.6132, -100.1712]}
          />
          <mesh geometry={nodes.Plane007.geometry} material={materials.Chrome} position={[0, -1.6132, -100.1712]} />
          <mesh material-color={props.exterior} geometry={nodes.Plane006.geometry} material={materials.paint} position={[0, -1.6132, -100.1712]} />
          <mesh geometry={nodes.Plane005.geometry} material={materials.paint} position={[0, -1.6132, -100.1712]} />
          <mesh geometry={nodes.Plane004.geometry} material={materials.paint} position={[0, -1.6132, -100.1712]} />
          <mesh geometry={nodes.Plane.geometry} material={materials.paint} position={[0, -1.6132, -100.1712]} />
          <mesh
            geometry={nodes.Plane001.geometry}
            material={materials['Chrome.003']}
            position={[0, -1.6132, -100.1712]}
          />
          <mesh
            geometry={nodes.Cube001.geometry}
            material={materials['Material.002']}
            position={[-46.9245, -0.4904, 177.1505]}
          />
          <mesh
            geometry={nodes.Sphere002.geometry}
            material={materials['Chrome.002']}
            position={[-46.229, 1.0236, 176.4751]}
            rotation={[-1.6472, 0.0909, 0.0982]}
            scale={[0.0069, 0.0069, 0.0069]}
          />
          <mesh
            geometry={nodes.Plane022.geometry}
            material={materials['Material.004']}
            position={[-36.878, -0.4959, 179.8525]}
          />
          <mesh geometry={nodes.Cube003.geometry} material={materials.Rubber} position={[-34.1141, 20.945, 110.9615]} />
          <mesh geometry={nodes.Cube004.geometry} material={materials.Chrome} position={[-34.1141, 20.945, 110.9615]} />
          <mesh geometry={nodes.Plane039.geometry} material={materials.Chrome} position={[0, -1.6132, -100.1712]} />
          <mesh geometry={nodes.Plane040.geometry} material={materials.Chrome} position={[0, -1.6132, -99.3487]} />
          <mesh geometry={nodes.Cube018.geometry} material={materials.Chrome} position={[-61.811, 19.1741, 53.761]} />
          <mesh geometry={nodes.Plane042.geometry} material={materials.Rubber} position={[0, -1.6132, -100.1712]} />
          <mesh
            geometry={nodes.Plane043.geometry}
            material={materials['Cristal.001']}
            position={[-63.9331, 18.9587, -20.1118]}
            scale={[-0.0772, 0.0772, 0.0772]}
          />
          <mesh
            geometry={nodes.Plane046.geometry}
            material={materials['Cristal.001']}
            position={[-63.6831, 18.5198, 13.7754]}
          />
          <mesh
            geometry={nodes.Cube021.geometry}
            material={materials.Chrome}
            position={[-57.1778, -18.8341, 174.9769]}
          />
          <mesh
            geometry={nodes.Plane048.geometry}
            material={materials['Material.011']}
            position={[1.0092, -20.6484, 2.1131]}
            rotation={[-Math.PI, 0, 0]}
          />
          <mesh geometry={nodes.Plane049.geometry} material={materials.Chrome} position={[0, -1.6132, -100.1712]} />
          <mesh
            geometry={nodes.Cube029.geometry}
            material={materials.Chrome}
            position={[-60.9016, 19.9153, -70.5446]}
            rotation={[-0.0147, 0, 0]}
          />
          <mesh
            geometry={nodes.Cube031.geometry}
            material={materials.Chrome}
            position={[-61.8425, 19.8199, -70.427]}
            rotation={[0, 0.1456, 0]}
          />
          <mesh
            geometry={nodes.Cube032.geometry}
            material={materials.Rubber}
            position={[-60.9016, 19.9153, -70.5446]}
            rotation={[-0.0147, 0, 0]}
          />
          <mesh
            geometry={nodes.Cube033.geometry}
            material={materials['Chrome.003']}
            position={[-61.8425, 19.8199, -70.427]}
            rotation={[0, 0.1456, 0]}
          />
          <mesh
            geometry={nodes.Sphere.geometry}
            material={materials.lightbulb}
            position={[-49.4149, 1.9619, -161.8472]}
            scale={[0.0204, 0.0204, 0.0204]}
          />
          <mesh
            geometry={nodes.Plane052.geometry}
            material={materials['Rubber.003']}
            position={[-48.9345, -9.1039, -169.4843]}
          />
          <mesh geometry={nodes.Plane011.geometry} material={materials.Chrome} position={[0, -17.5222, -180.9241]} />
          <mesh geometry={nodes.Plane047.geometry} material={materials.Rubber} position={[0, -17.5222, -179.4241]} />
          <mesh geometry={nodes.Plane017.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Plane021.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Cylinder014.geometry} material={materials.Rubber} position={[0, -16.6111, -27.8881]} />
          <mesh
            geometry={nodes.Cube024.geometry}
            material={materials.Rubber}
            position={[-20.5913, -24.1731, -72.6928]}
            rotation={[-0.3439, 0, 0]}
          />
          <mesh
            geometry={nodes.Cube023.geometry}
            material={materials.Rubber}
            position={[-27.7815, -24.1731, -72.6928]}
            rotation={[-0.3439, 0, 0]}
          />
          <mesh
            geometry={nodes.Cube027.geometry}
            material={materials['metal.001']}
            position={[-12.1065, -24.2516, -75.5386]}
            rotation={[-0.3575, 0, 0]}
          />
          <mesh
            geometry={nodes.Cylinder008.geometry}
            material={materials['Rubber.001']}
            position={[-27.4785, 10.4125, -27.1013]}
            rotation={[1.0724, 0, 0]}
          />
          <mesh
            geometry={nodes.Cylinder009.geometry}
            material={materials['Material.007']}
            position={[-27.4785, 10.4125, -27.1013]}
            rotation={[1.0724, 0, 0]}
            scale={[0.0522, 0.0522, 0.0522]}
          />
          <mesh
            geometry={nodes.Cube011.geometry}
            material={nodes.Cube011.material}
            position={[-36.4219, 14.1388, -41.2747]}
            rotation={[-0.1157, 0.0358, 0.5845]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.Cube012.geometry}
            material={nodes.Cube012.material}
            position={[-17.5023, 14.1388, -42.8791]}
            rotation={[-0.1308, 0.0317, 0.4576]}
            scale={[1, 1, 1]}
          />
          <mesh geometry={nodes.Plane026.geometry} material={materials.Rubber} position={[0, -1.6132, -100.1712]} />
          <mesh
            geometry={nodes.Plane015.geometry}
            material={materials.Chrome}
            position={[-61.4683, -29.1479, -98.9785]}
          />
          <mesh
            geometry={nodes.Cylinder.geometry}
            material={materials.metal}
            position={[-57.9152, -0.8491, 178.3433]}
            rotation={[0.0384, -0.1046, 0.0047]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.Bolt.geometry}
            material={materials.metal}
            position={[-60.9016, 20.1972, -74.7472]}
            scale={[0.1322, 0.0766, 0.1322]}
          />
          <mesh
            geometry={nodes.Bolt001.geometry}
            material={materials.metal}
            position={[-61.9846, 20.253, -68.8568]}
            scale={[0.1322, 0.0766, 0.1322]}
          />
          <mesh
            geometry={nodes.Bolt002.geometry}
            material={materials.metal}
            position={[-59.8339, 20.253, -68.8568]}
            rotation={[Math.PI, -1.439, Math.PI]}
            scale={[0.1322, 0.0766, 0.1322]}
          />
          <mesh geometry={nodes.Plane019.geometry} material={materials.metal} />
          <mesh geometry={nodes.Plane020.geometry} material={materials.metal} />
          <mesh
            geometry={nodes.Plane035.geometry}
            material={materials.metal}
            position={[-27.0694, 12.5684, -40.7425]}
            scale={[1.275, 1.275, 1.275]}
          />
          <mesh
            geometry={nodes.Cube025.geometry}
            material={materials.metal}
            position={[-20.4813, -20.4176, -74.2081]}
          />
          <mesh
            geometry={nodes.Cube026.geometry}
            material={materials.metal}
            position={[-27.6714, -20.4176, -74.2081]}
          />
          <mesh
            geometry={nodes.Plane045.geometry}
            material={materials['Material.010']}
            position={[32.0662, -32.086, -47.3348]}
          />
          <mesh geometry={nodes.Plane018.geometry} material={materials.Wood} />
          <mesh
            geometry={nodes.Torus.geometry}
            material={materials.Wood}
            position={[-27.4785, 13.0986, -22.6238]}
            rotation={[1.0304, 0, 0]}
            scale={[0.8876, 0.8876, 0.8876]}
          />
          <mesh geometry={nodes.Plane008.geometry} material={materials.Cristal} position={[0, -1.6132, -100.1712]} />
          <mesh
            geometry={nodes.Cube008.geometry}
            material={materials.Seats}
            position={[-31.1222, -32.9726, 10.2407]}
            rotation={[0.0777, 0, 0]}>
            <mesh material-color={props.interior} geometry={nodes.Cube005.geometry} material={materials.Seats} />
            <mesh
              geometry={nodes.Cube009_1.geometry}
              material={materials.metal}
              position={[2.163, 0, 0]}
              rotation={[-0.0777, 0, 0]}
            />
            <mesh
              geometry={nodes.Cube010.geometry}
              material={materials.metal}
              position={[-13.6882, 1.299, 11.4763]}
              rotation={[-0.0777, 0, 0]}
            />
          </mesh>
          <mesh geometry={nodes.Plane027.geometry} material={materials['matte-black']} />
          <mesh
            geometry={nodes.Cube013.geometry}
            material={materials['matte-black']}
            position={[-22.3986, 2.1224, -41.9283]}
            rotation={[-0.1147, -0.0196, -0.045]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.Cube015.geometry}
            material={materials['matte-black']}
            position={[-0.5918, -14.4786, -64.9295]}
          />
          <mesh geometry={nodes.Plane024.geometry} material={materials['matte-black']} />
          <mesh
            geometry={nodes.Cube020.geometry}
            material={materials['matte-black']}
            position={[0, -17.6559, -4.7609]}
          />
          <mesh
            geometry={nodes.Cube014.geometry}
            material={materials['matte-black']}
            position={[-27.2349, -13.2871, -73.328]}
            rotation={[-0.2408, 0, 0]}
          />
          <mesh
            geometry={nodes.Cylinder001.geometry}
            material={materials['matte-black']}
            position={[-36.426, 14.1255, -41.3891]}
            rotation={[1.4788, 0.5841, -0.0429]}
            scale={[0.0044, 0.0044, 0.0044]}
          />
          <mesh
            geometry={nodes.Cylinder002.geometry}
            material={materials['matte-black']}
            position={[-17.5064, 14.1255, -42.9935]}
            rotation={[1.4788, 0.5841, -0.0429]}
            scale={[0.0044, 0.0044, 0.0044]}
          />
          <mesh material-color={props.interior} geometry={nodes.Plane025.geometry} material={materials['matte-black']} />
          <mesh
            geometry={nodes.Cylinder010.geometry}
            material={materials['Rubber.002']}
            position={[-27.4785, 10.4125, -27.1013]}
            rotation={[1.0724, 0, 0]}
            scale={[0.0522, 0.0522, 0.0522]}
          />
          <mesh
            geometry={nodes.Plane029.geometry}
            material={materials['Cristal.002']}
            position={[-18.65, 0.0822, 1.6076]}
          />
          <mesh geometry={nodes.Plane034.geometry} material={materials['Cristal.002']} />
          <mesh
            geometry={nodes.Plane037.geometry}
            material={materials['Cristal.002']}
            position={[-17.7719, -0.1327, 1.5559]}
          />
          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials['metal.002']}
            position={[-61.4683, -29.1479, -98.9785]}
          />
          <mesh
            geometry={nodes.Cube035.geometry}
            material={materials.Exhaust}
            position={[-29.1792, -36.2673, 151.3588]}
            scale={[1.2392, 1.2392, 1.2392]}
          />
          <mesh
            geometry={nodes.Cylinder018.geometry}
            material={materials.Exhaust}
            position={[-32.2592, -36.4308, 158.8451]}
            scale={[1.2392, 1.2392, 1.2392]}
          />
          <mesh
            geometry={nodes.Cylinder019.geometry}
            material={materials.Exhaust}
            position={[-25.883, -36.4308, 158.8451]}
            scale={[1.2392, 1.2392, 1.2392]}
          />
        </group>
      </group>
    </group>
  )
}


useGLTF.preload('/scene.gltf')