# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/prototype"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "npm"
      - "dependencies"
    assignees:
      - "longtv2222"
    # Prefix all commit messages with "npm"
    # include a list of updated dependencies
    commit-message:
      prefix: "npm"
      include: "scope"