pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Test React 
      - check-success=Test AWS Infrastructure
    actions:
      merge:
        method: squash
      delete_head_branch: #Delete head branch after merge
