/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.4, 0]} scale={[0.02, 0.02, 0.02]}>
        <group position={[0, -17.52, 177.45]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Plane012_1.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Plane012_2.geometry} material={materials.Chrome} />
        </group>
        <group position={[-34.27, 22.24, 81.9]} rotation={[0.01, 0, 0.06]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.Cube006_1.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Cube006_2.geometry} material={materials.Rubber} />
        </group>
        <group position={[0, 23.06, 82.35]} rotation={[0.02, 0, 0]}>
          <mesh geometry={nodes.Cube008_1.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Cube008_2.geometry} material={materials.Rubber} />
        </group>
        <group position={[0, -1.61, -100.17]}>
          <mesh geometry={nodes.Plane044_1.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Plane044_2.geometry} material={materials.Rubber} />
        </group>
        <group position={[-63.93, 18.96, -20.11]} scale={[-0.08, 0.08, 0.08]}>
          <mesh geometry={nodes.Plane047_1.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Plane047_2.geometry} material={materials.Rubber} />
        </group>
        <group position={[0.01, 46.69, -20.07]} rotation={[0.3, -0.25, 0.08]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.Cube011_1.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Cube011_2.geometry} material={materials['Chrome.003']} />
        </group>
        <group position={[-4.06, -0.48, -49.64]}>
          <mesh geometry={nodes.Cube022_1.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Cube022_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[1.14, -19.08, 3.84]}>
          <mesh geometry={nodes.Cube034.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Cube034_1.geometry} material={materials.Rubber} />
        </group>
        <group position={[-60.17, -5.07, -12.93]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[3.06, 0.47, 9.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes.Cube024_1.geometry} material={materials['Rubber.001']} />
            <mesh geometry={nodes.Cube024_2.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Cube024_3.geometry} material={materials['matte-black']} />
          </group>
          <mesh geometry={nodes.Plane040_1.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Plane040_2.geometry} material={materials.Chrome} />
          <mesh
            geometry={nodes.Plane038.geometry}
            material={materials.metal}
            position={[1.95, 0.84, -12.72]}
            rotation={[0, 0.06, Math.PI / 2]}
            scale={[1.34, 1.34, 1.34]}
          />
        </group>
        <group position={[-59.95, -7.38, -38.8]} rotation={[2.75, 0, -Math.PI / 2]} scale={[0.02, 0.02, 0.02]}>
          <mesh geometry={nodes.Cylinder032.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Cylinder032_1.geometry} material={materials.Rubber} />
        </group>
        <group position={[0, -1.61, -100.17]}>
          <mesh geometry={nodes.Plane003.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.003']} />
        </group>
        <group position={[-61.47, -29.15, -98.98]}>
          <mesh geometry={nodes.Plane014_2.geometry} material={materials.tire_tread} />
          <mesh geometry={nodes.Plane014_1.geometry} material={materials.tire_side} />
        </group>
        <group position={[-22.28, 21.3, 111.25]} rotation={[0.08, 0, 0]} scale={[0.81, 0.81, 0.81]}>
          <mesh geometry={nodes.Cylinder038.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder038_1.geometry} material={materials.Rubber} />
        </group>
        <group position={[-10.16, 53.93, -18.29]}>
          <mesh geometry={nodes.Cube030_1.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cube030_2.geometry} material={materials.Rubber} />
        </group>
        <group position={[0.01, 51.89, -20.95]}>
          <mesh geometry={nodes.Cube007_1.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Cube007_2.geometry} material={materials.metal} />
        </group>
        <group position={[0, 7.22, -40.97]} rotation={[1.31, 0, 0]}>
          <mesh geometry={nodes.Cylinder030.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder030_1.geometry} material={materials.Rubber} />
        </group>
        <group position={[-4.73, 7.26, -40.79]} rotation={[1.35, 0, 0]}>
          <mesh geometry={nodes.Cylinder031.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder031_1.geometry} material={materials.Rubber} />
        </group>
        <group position={[-0.76, -12.1, -28.81]} rotation={[-0.17, -0.16, 0.17]} scale={[0.01, 0.01, 0.01]}>
          <group position={[0, 2121.53, 0.06]} scale={[131.16, 131.16, 131.16]}>
            <mesh geometry={nodes.Cylinder037_1.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder037.geometry} material={materials['matte-black']} />
          </group>
          <mesh geometry={nodes.Cylinder036.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder036_1.geometry} material={materials.Rubber} />
        </group>
        <mesh geometry={nodes.Plane029_1.geometry} material={materials['matte-black']} />
        <mesh geometry={nodes.Plane029_2.geometry} material={materials.Cluster} />
        <group position={[-17.77, -0.13, 1.56]}>
          <mesh geometry={nodes.Plane030_1.geometry} material={materials['matte-black']} />
          <mesh geometry={nodes.Plane030_2.geometry} material={materials.Cluster} />
        </group>
        <group position={[-24.48, -0.44, 2.17]}>
          <mesh geometry={nodes.Plane031_1.geometry} material={materials['matte-black']} />
          <mesh geometry={nodes.Plane031_2.geometry} material={materials.Cluster} />
        </group>
        <group position={[-18.65, 0.08, 1.61]}>
          <mesh geometry={nodes.Plane032_1.geometry} material={materials['matte-black']} />
          <mesh geometry={nodes.Plane032_2.geometry} material={materials.Cluster} />
        </group>
        <mesh geometry={nodes.Plane033_1.geometry} material={materials['matte-black']} />
        <mesh geometry={nodes.Plane033_2.geometry} material={materials.Cluster} />
        <group position={[-69.8, 7.39, 38.82]} scale={[1.21, 1.21, 1.21]}>
          <mesh geometry={nodes.Plane025_1.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Plane025_2.geometry} material={materials.metal} />
          <mesh geometry={nodes.Plane025_3.geometry} material={materials['matte-black']} />
        </group>
        <group position={[-17.01, 2.52, -40.24]} rotation={[1.03, 0, 0]}>
          <mesh geometry={nodes.Cylinder021.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder021_1.geometry} material={materials['matte-black']} />
        </group>
        <group position={[-51.88, 12.16, -38.8]} rotation={[1.58, 0.01, -0.08]} scale={[0.01, 0.01, 0.01]}>
          <mesh geometry={nodes.Cylinder016_1.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder016_2.geometry} material={materials['matte-black']} />
        </group>
        <group position={[-49.04, 12.16, -39.05]} rotation={[1.58, 0.01, -0.09]} scale={[0.01, 0.01, 0.01]}>
          <mesh geometry={nodes.Cylinder016_1_1.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder016_2_1.geometry} material={materials['matte-black']} />
        </group>
        <group position={[-46.19, 12.16, -39.29]} rotation={[1.58, 0.01, -0.09]} scale={[0.01, 0.01, 0.01]}>
          <mesh geometry={nodes.Cylinder016_1_2.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder016_2_2.geometry} material={materials['matte-black']} />
        </group>
        <group position={[-43.35, 12.16, -39.54]} rotation={[1.58, 0.01, -0.09]} scale={[0.01, 0.01, 0.01]}>
          <mesh geometry={nodes.Cylinder016_1_3.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cylinder016_2_3.geometry} material={materials['matte-black']} />
        </group>
        <mesh geometry={nodes.Plane013.geometry} material={materials.Chrome} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane010.geometry} material={materials.Rubber} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane009.geometry} material={materials['Cristal.001']} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane007.geometry} material={materials.Chrome} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane006.geometry} material={materials.paint} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane005.geometry} material={materials.paint} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane004.geometry} material={materials.paint} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane.geometry} material={materials.paint} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane001.geometry} material={materials['Chrome.003']} position={[0, -1.61, -100.17]} />
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials['Material.002']}
          position={[-46.92, -0.49, 177.15]}
        />
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={materials['Chrome.002']}
          position={[-46.23, 1.02, 176.48]}
          rotation={[-1.65, 0.09, 0.1]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          geometry={nodes.Plane022.geometry}
          material={materials['Material.004']}
          position={[-36.88, -0.5, 179.85]}
        />
        <mesh geometry={nodes.Cube003.geometry} material={materials.Rubber} position={[-34.11, 20.94, 110.96]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials.Chrome} position={[-34.11, 20.94, 110.96]} />
        <mesh geometry={nodes.Plane039.geometry} material={materials.Chrome} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane040.geometry} material={materials.Chrome} position={[0, -1.61, -99.35]} />
        <mesh geometry={nodes.Cube018.geometry} material={materials.Chrome} position={[-61.81, 19.17, 53.76]} />
        <mesh geometry={nodes.Plane042.geometry} material={materials.Rubber} position={[0, -1.61, -100.17]} />
        <mesh
          geometry={nodes.Plane043.geometry}
          material={materials['Cristal.001']}
          position={[-63.93, 18.96, -20.11]}
          scale={[-0.08, 0.08, 0.08]}
        />
        <mesh
          geometry={nodes.Plane046.geometry}
          material={materials['Cristal.001']}
          position={[-63.68, 18.52, 13.78]}
        />
        <mesh geometry={nodes.Cube021.geometry} material={materials.Chrome} position={[-57.18, -18.83, 174.98]} />
        <mesh
          geometry={nodes.Plane048.geometry}
          material={materials['Material.011']}
          position={[1.01, -20.65, 2.11]}
          rotation={[-Math.PI, 0, 0]}
        />
        <mesh geometry={nodes.Plane049.geometry} material={materials.Chrome} position={[0, -1.61, -100.17]} />
        <mesh
          geometry={nodes.Cube029.geometry}
          material={materials.Chrome}
          position={[-60.9, 19.92, -70.54]}
          rotation={[-0.01, 0, 0]}
        />
        <mesh
          geometry={nodes.Cube031.geometry}
          material={materials.Chrome}
          position={[-61.84, 19.82, -70.43]}
          rotation={[0, 0.15, 0]}
        />
        <mesh
          geometry={nodes.Cube032.geometry}
          material={materials.Rubber}
          position={[-60.9, 19.92, -70.54]}
          rotation={[-0.01, 0, 0]}
        />
        <mesh
          geometry={nodes.Cube033.geometry}
          material={materials['Chrome.003']}
          position={[-61.84, 19.82, -70.43]}
          rotation={[0, 0.15, 0]}
        />
        <mesh
          geometry={nodes.Sphere.geometry}
          material={materials.lightbulb}
          position={[-49.41, 1.96, -161.85]}
          scale={[0.02, 0.02, 0.02]}
        />
        <mesh
          geometry={nodes.Plane052.geometry}
          material={materials['Rubber.003']}
          position={[-48.93, -9.1, -169.48]}
        />
        <mesh geometry={nodes.Plane011.geometry} material={materials.Chrome} position={[0, -17.52, -180.92]} />
        <mesh geometry={nodes.Plane047.geometry} material={materials.Rubber} position={[0, -17.52, -179.42]} />
        <mesh geometry={nodes.Plane017.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Plane021.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Cylinder014.geometry} material={materials.Rubber} position={[0, -16.61, -27.89]} />
        <mesh
          geometry={nodes.Cube024.geometry}
          material={materials.Rubber}
          position={[-20.59, -24.17, -72.69]}
          rotation={[-0.34, 0, 0]}
        />
        <mesh
          geometry={nodes.Cube023.geometry}
          material={materials.Rubber}
          position={[-27.78, -24.17, -72.69]}
          rotation={[-0.34, 0, 0]}
        />
        <mesh
          geometry={nodes.Cube027.geometry}
          material={materials['metal.001']}
          position={[-12.11, -24.25, -75.54]}
          rotation={[-0.36, 0, 0]}
        />
        <mesh
          geometry={nodes.Cylinder008.geometry}
          material={materials['Rubber.001']}
          position={[-27.48, 10.41, -27.1]}
          rotation={[1.07, 0, 0]}
        />
        <mesh
          geometry={nodes.Cylinder009.geometry}
          material={materials['Material.007']}
          position={[-27.48, 10.41, -27.1]}
          rotation={[1.07, 0, 0]}
          scale={[0.05, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Cube011.geometry}
          material={nodes.Cube011.material}
          position={[-36.42, 14.14, -41.27]}
          rotation={[-0.12, 0.04, 0.58]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Cube012.geometry}
          material={nodes.Cube012.material}
          position={[-17.5, 14.14, -42.88]}
          rotation={[-0.13, 0.03, 0.46]}
          scale={[1, 1, 1]}
        />
        <mesh geometry={nodes.Plane026.geometry} material={materials.Rubber} position={[0, -1.61, -100.17]} />
        <mesh geometry={nodes.Plane015.geometry} material={materials.Chrome} position={[-61.47, -29.15, -98.98]} />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials.metal}
          position={[-57.92, -0.85, 178.34]}
          rotation={[0.04, -0.1, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Bolt.geometry}
          material={materials.metal}
          position={[-60.9, 20.2, -74.75]}
          scale={[0.13, 0.08, 0.13]}
        />
        <mesh
          geometry={nodes.Bolt001.geometry}
          material={materials.metal}
          position={[-61.98, 20.25, -68.86]}
          scale={[0.13, 0.08, 0.13]}
        />
        <mesh
          geometry={nodes.Bolt002.geometry}
          material={materials.metal}
          position={[-59.83, 20.25, -68.86]}
          rotation={[Math.PI, -1.44, Math.PI]}
          scale={[0.13, 0.08, 0.13]}
        />
        <mesh geometry={nodes.Plane019.geometry} material={materials.metal} />
        <mesh geometry={nodes.Plane020.geometry} material={materials.metal} />
        <mesh
          geometry={nodes.Plane035.geometry}
          material={materials.metal}
          position={[-27.07, 12.57, -40.74]}
          scale={[1.28, 1.28, 1.28]}
        />
        <mesh geometry={nodes.Cube025.geometry} material={materials.metal} position={[-20.48, -20.42, -74.21]} />
        <mesh geometry={nodes.Cube026.geometry} material={materials.metal} position={[-27.67, -20.42, -74.21]} />
        <mesh
          geometry={nodes.Plane045.geometry}
          material={materials['Material.010']}
          position={[32.07, -32.09, -47.33]}
        />
        <mesh geometry={nodes.Plane018.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Torus.geometry}
          material={materials.Wood}
          position={[-27.48, 13.1, -22.62]}
          rotation={[1.03, 0, 0]}
          scale={[0.89, 0.89, 0.89]}
        />
        <mesh geometry={nodes.Plane008.geometry} material={materials.Cristal} position={[0, -1.61, -100.17]} />
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials.Seats}
          position={[-31.12, -32.97, 10.24]}
          rotation={[0.08, 0, 0]}>
          <mesh geometry={nodes.Cube005.geometry} material={materials.Seats} />
          <mesh
            geometry={nodes.Cube009_1.geometry}
            material={materials.metal}
            position={[2.16, 0, 0]}
            rotation={[-0.08, 0, 0]}
          />
          <mesh
            geometry={nodes.Cube010.geometry}
            material={materials.metal}
            position={[-13.69, 1.3, 11.48]}
            rotation={[-0.08, 0, 0]}
          />
        </mesh>
        <mesh geometry={nodes.Plane027.geometry} material={materials['matte-black']} />
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials['matte-black']}
          position={[-22.4, 2.12, -41.93]}
          rotation={[-0.11, -0.02, -0.05]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Cube015.geometry}
          material={materials['matte-black']}
          position={[-0.59, -14.48, -64.93]}
        />
        <mesh geometry={nodes.Plane024.geometry} material={materials['matte-black']} />
        <mesh geometry={nodes.Cube020.geometry} material={materials['matte-black']} position={[0, -17.66, -4.76]} />
        <mesh
          geometry={nodes.Cube014.geometry}
          material={materials['matte-black']}
          position={[-27.23, -13.29, -73.33]}
          rotation={[-0.24, 0, 0]}
        />
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials['matte-black']}
          position={[-36.43, 14.13, -41.39]}
          rotation={[1.48, 0.58, -0.04]}
          scale={[0, 0, 0]}
        />
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials['matte-black']}
          position={[-17.51, 14.13, -42.99]}
          rotation={[1.48, 0.58, -0.04]}
          scale={[0, 0, 0]}
        />
        <mesh geometry={nodes.Plane025.geometry} material={materials['matte-black']} />
        <mesh
          geometry={nodes.Cylinder010.geometry}
          material={materials['Rubber.002']}
          position={[-27.48, 10.41, -27.1]}
          rotation={[1.07, 0, 0]}
          scale={[0.05, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Cube035.geometry}
          material={materials.Exhaust}
          position={[-29.18, -36.27, 151.36]}
          scale={[1.24, 1.24, 1.24]}
        />
        <mesh
          geometry={nodes.Cylinder018.geometry}
          material={materials.Exhaust}
          position={[-32.26, -36.43, 158.85]}
          scale={[1.24, 1.24, 1.24]}
        />
        <mesh
          geometry={nodes.Cylinder019.geometry}
          material={materials.Exhaust}
          position={[-25.88, -36.43, 158.85]}
          scale={[1.24, 1.24, 1.24]}
        />
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials['metal.002']}
          position={[-61.47, -29.15, -98.98]}
        />
        <mesh geometry={nodes.Plane029.geometry} material={materials['Cristal.002']} position={[-18.65, 0.08, 1.61]} />
        <mesh geometry={nodes.Plane034.geometry} material={materials['Cristal.002']} />
        <mesh geometry={nodes.Plane037.geometry} material={materials['Cristal.002']} position={[-17.77, -0.13, 1.56]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
