on:
  release:
    types: [created]
name: Build and Deploy
jobs:
  deploy:
    name: Deploy AWS Resources
    runs-on: ubuntu-latest
    environment:
      name: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and Caching
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: |
            infrastructure/package-lock.json
            prototype/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Build React project
        run: |
          npm ci
          npm run build
        working-directory: prototype

      - name: Run deployment job
        run: |
          npm ci
          npm run deploy-prod-frontend
        working-directory: infrastructure
