on: push
name: Build and Deploy
jobs:
  deploy:
    name: Deploy AWS Resources
    runs-on: ubuntu-latest
    environment:
      name: AWS Credentials

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build React project
        run: |
          cd prototype
          npm ci
          npm run build

      - name: Run deployment job
        run: |
          cd infrastructure
          npm ci
          npm run cdk -- --version
